version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: extrums-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '6500:5432'

  api:
    depends_on:
      - postgres
    build: ./back
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:1234@postgres/extrums-db?schema=public
