version: '3.8'
services:
  db:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: ./back
    container_name: api_backend
    ports:
      - '4000:4000'
    env_file:
      - back/.env

  client:
    depends_on:
      - api
    build: ./front
    container_name: frontend
    ports:
      - '3000:3000'
    env_file:
      - front/.env