version: '3.8'
services:
  db:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    depends_on:
      - db
    build: ./back
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
    env_file:
      - back/.env
    stdin_open: true
    tty: true
    networks:
      - my_network

volumes:
  data:

networks:
  my_network:
    driver: bridge